[2020-06-11 02:45:23,844] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: dataops.modeling 2020-06-11T00:00:00+00:00 [queued]>
[2020-06-11 02:45:23,894] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: dataops.modeling 2020-06-11T00:00:00+00:00 [queued]>
[2020-06-11 02:45:23,894] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-11 02:45:23,894] {taskinstance.py:880} INFO - Starting attempt 1 of 4
[2020-06-11 02:45:23,894] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-11 02:45:23,924] {taskinstance.py:900} INFO - Executing <Task(BashOperator): modeling> on 2020-06-11T00:00:00+00:00
[2020-06-11 02:45:23,927] {standard_task_runner.py:53} INFO - Started process 6007 to run task
[2020-06-11 02:45:23,994] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: dataops.modeling 2020-06-11T00:00:00+00:00 [running]> vinicius-Latitude-3480
[2020-06-11 02:45:24,019] {bash_operator.py:82} INFO - Tmp dir root location: 
 /tmp
[2020-06-11 02:45:24,020] {bash_operator.py:105} INFO - Temporary script location: /tmp/airflowtmpbikmhd6q/modelingbckqjeq2
[2020-06-11 02:45:24,020] {bash_operator.py:115} INFO - Running command: python /home/vinicius/Documents/Projetos/Claro/Piloto/git_Homologação/src/modeling/run.py
[2020-06-11 02:45:24,026] {bash_operator.py:122} INFO - Output:
[2020-06-11 02:46:46,650] {bash_operator.py:126} INFO - Treinando modelo KNeighborsRegressor
[2020-06-11 02:46:46,651] {bash_operator.py:126} INFO - INFO: 'Test_model' does not exist. Creating a new experiment
[2020-06-11 02:46:46,651] {bash_operator.py:126} INFO - Treinando modelo LinearRegression
[2020-06-11 02:46:46,667] {bash_operator.py:126} INFO - Traceback (most recent call last):
[2020-06-11 02:46:46,668] {bash_operator.py:126} INFO -   File "/home/vinicius/Documents/Projetos/Claro/Piloto/git_Homologação/src/modeling/run.py", line 106, in <module>
[2020-06-11 02:46:46,668] {bash_operator.py:126} INFO -     save_output(config_model,list_result,output_dict)
[2020-06-11 02:46:46,669] {bash_operator.py:126} INFO -   File "/home/vinicius/Documents/Projetos/Claro/Piloto/git_Homologação/src/modeling/run.py", line 51, in save_output
[2020-06-11 02:46:46,669] {bash_operator.py:126} INFO -     output_table.to_csv(f"{output_table_path}/{output_table_name}")
[2020-06-11 02:46:46,669] {bash_operator.py:126} INFO -   File "/home/vinicius/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py", line 3228, in to_csv
[2020-06-11 02:46:46,670] {bash_operator.py:126} INFO -     formatter.save()
[2020-06-11 02:46:46,670] {bash_operator.py:126} INFO -   File "/home/vinicius/anaconda3/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 183, in save
[2020-06-11 02:46:46,670] {bash_operator.py:126} INFO -     compression=self.compression,
[2020-06-11 02:46:46,671] {bash_operator.py:126} INFO -   File "/home/vinicius/anaconda3/lib/python3.7/site-packages/pandas/io/common.py", line 399, in _get_handle
[2020-06-11 02:46:46,671] {bash_operator.py:126} INFO -     f = open(path_or_buf, mode, encoding=encoding, newline="")
[2020-06-11 02:46:46,671] {bash_operator.py:126} INFO - FileNotFoundError: [Errno 2] No such file or directory: 'output/model_output_54406.csv'
[2020-06-11 02:46:47,093] {bash_operator.py:130} INFO - Command exited with return code 1
[2020-06-11 02:46:47,106] {taskinstance.py:1145} ERROR - Bash command failed
Traceback (most recent call last):
  File "/home/vinicius/anaconda3/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/vinicius/anaconda3/lib/python3.7/site-packages/airflow/operators/bash_operator.py", line 134, in execute
    raise AirflowException("Bash command failed")
airflow.exceptions.AirflowException: Bash command failed
[2020-06-11 02:46:47,108] {taskinstance.py:1168} INFO - Marking task as UP_FOR_RETRY
[2020-06-11 02:46:49,961] {logging_mixin.py:112} INFO - [2020-06-11 02:46:49,960] {local_task_job.py:103} INFO - Task exited with return code 1
