[2020-06-12 15:58:53,322] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: dataops.modeling 2020-06-11T00:00:00+00:00 [queued]>
[2020-06-12 15:58:53,348] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: dataops.modeling 2020-06-11T00:00:00+00:00 [queued]>
[2020-06-12 15:58:53,349] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-12 15:58:53,349] {taskinstance.py:880} INFO - Starting attempt 18 of 20
[2020-06-12 15:58:53,349] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-12 15:58:53,371] {taskinstance.py:900} INFO - Executing <Task(BashOperator): modeling> on 2020-06-11T00:00:00+00:00
[2020-06-12 15:58:53,374] {standard_task_runner.py:53} INFO - Started process 29269 to run task
[2020-06-12 15:58:53,462] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: dataops.modeling 2020-06-11T00:00:00+00:00 [running]> vinicius-Latitude-3480
[2020-06-12 15:58:53,486] {bash_operator.py:82} INFO - Tmp dir root location: 
 /tmp
[2020-06-12 15:58:53,488] {bash_operator.py:103} INFO - Temporary script location: /tmp/airflowtmpuozpbsf5/modelingzkbbbi6s
[2020-06-12 15:58:53,488] {bash_operator.py:115} INFO - Running command: python /home/vinicius/Documents/Projetos/Claro/Piloto/git_Homologação/src/modeling/run.py
[2020-06-12 15:58:53,494] {bash_operator.py:122} INFO - Output:
[2020-06-12 15:58:59,946] {helpers.py:325} INFO - Sending Signals.SIGTERM to GPID 29269
[2020-06-12 15:58:59,946] {taskinstance.py:954} ERROR - Received SIGTERM. Terminating subprocesses.
[2020-06-12 15:58:59,947] {bash_operator.py:140} INFO - Sending SIGTERM signal to bash process group
[2020-06-12 15:58:59,969] {taskinstance.py:1145} ERROR - Task received SIGTERM signal
Traceback (most recent call last):
  File "/home/vinicius/anaconda3/envs/claro_piloto_homolog/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/vinicius/anaconda3/envs/claro_piloto_homolog/lib/python3.8/site-packages/airflow/operators/bash_operator.py", line 124, in execute
    for line in iter(self.sub_process.stdout.readline, b''):
  File "/home/vinicius/anaconda3/envs/claro_piloto_homolog/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 956, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2020-06-12 15:58:59,973] {taskinstance.py:1168} INFO - Marking task as UP_FOR_RETRY
[2020-06-12 15:59:00,055] {helpers.py:291} INFO - Process psutil.Process(pid=29277, status='terminated') (29277) terminated with exit code None
[2020-06-12 15:59:00,055] {helpers.py:291} INFO - Process psutil.Process(pid=29276, status='terminated') (29276) terminated with exit code None
[2020-06-12 15:59:00,056] {helpers.py:291} INFO - Process psutil.Process(pid=29269, status='terminated') (29269) terminated with exit code 1
