[2020-06-12 16:47:42,754] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: dataops.modeling 2020-06-11T00:00:00+00:00 [queued]>
[2020-06-12 16:47:42,784] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: dataops.modeling 2020-06-11T00:00:00+00:00 [queued]>
[2020-06-12 16:47:42,785] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-12 16:47:42,785] {taskinstance.py:880} INFO - Starting attempt 25 of 26
[2020-06-12 16:47:42,785] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-12 16:47:42,810] {taskinstance.py:900} INFO - Executing <Task(BashOperator): modeling> on 2020-06-11T00:00:00+00:00
[2020-06-12 16:47:42,812] {standard_task_runner.py:53} INFO - Started process 32743 to run task
[2020-06-12 16:47:42,890] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: dataops.modeling 2020-06-11T00:00:00+00:00 [running]> vinicius-Latitude-3480
[2020-06-12 16:47:42,915] {bash_operator.py:82} INFO - Tmp dir root location: 
 /tmp
[2020-06-12 16:47:42,916] {bash_operator.py:103} INFO - Temporary script location: /tmp/airflowtmpm9u3qiou/modelings2f65b5c
[2020-06-12 16:47:42,916] {bash_operator.py:115} INFO - Running command: python /home/vinicius/Documents/Projetos/Claro/Piloto/git_Homologação/src/modeling/run.py
[2020-06-12 16:47:42,924] {bash_operator.py:122} INFO - Output:
[2020-06-12 16:47:57,224] {helpers.py:325} INFO - Sending Signals.SIGTERM to GPID 32743
[2020-06-12 16:47:57,225] {taskinstance.py:954} ERROR - Received SIGTERM. Terminating subprocesses.
[2020-06-12 16:47:57,225] {bash_operator.py:140} INFO - Sending SIGTERM signal to bash process group
[2020-06-12 16:47:57,246] {taskinstance.py:1145} ERROR - Task received SIGTERM signal
Traceback (most recent call last):
  File "/home/vinicius/anaconda3/envs/claro_piloto_homolog/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/vinicius/anaconda3/envs/claro_piloto_homolog/lib/python3.8/site-packages/airflow/operators/bash_operator.py", line 124, in execute
    for line in iter(self.sub_process.stdout.readline, b''):
  File "/home/vinicius/anaconda3/envs/claro_piloto_homolog/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 956, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2020-06-12 16:47:57,247] {taskinstance.py:1168} INFO - Marking task as UP_FOR_RETRY
[2020-06-12 16:47:57,290] {helpers.py:291} INFO - Process psutil.Process(pid=32750, status='terminated') (32750) terminated with exit code None
[2020-06-12 16:47:57,291] {helpers.py:291} INFO - Process psutil.Process(pid=32743, status='terminated') (32743) terminated with exit code 1
[2020-06-12 16:47:57,390] {helpers.py:291} INFO - Process psutil.Process(pid=32751, status='terminated') (32751) terminated with exit code None
