[2020-06-12 16:48:53,916] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: dataops.modeling 2020-06-11T00:00:00+00:00 [queued]>
[2020-06-12 16:48:53,965] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: dataops.modeling 2020-06-11T00:00:00+00:00 [queued]>
[2020-06-12 16:48:53,966] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-12 16:48:53,966] {taskinstance.py:880} INFO - Starting attempt 26 of 29
[2020-06-12 16:48:53,966] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-12 16:48:53,997] {taskinstance.py:900} INFO - Executing <Task(BashOperator): modeling> on 2020-06-11T00:00:00+00:00
[2020-06-12 16:48:54,001] {standard_task_runner.py:53} INFO - Started process 638 to run task
[2020-06-12 16:48:54,084] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: dataops.modeling 2020-06-11T00:00:00+00:00 [running]> vinicius-Latitude-3480
[2020-06-12 16:48:54,109] {bash_operator.py:82} INFO - Tmp dir root location: 
 /tmp
[2020-06-12 16:48:54,110] {bash_operator.py:103} INFO - Temporary script location: /tmp/airflowtmpcajx9q1i/modelingoxvaqtpb
[2020-06-12 16:48:54,110] {bash_operator.py:115} INFO - Running command: python /home/vinicius/Documents/Projetos/Claro/Piloto/git_Homologação/src/modeling/run.py
[2020-06-12 16:48:54,117] {bash_operator.py:122} INFO - Output:
[2020-06-12 16:50:23,435] {bash_operator.py:126} INFO - Treinando modelo KN_Test_2
[2020-06-12 16:50:23,435] {bash_operator.py:126} INFO - Treinando modelo KN_4
[2020-06-12 16:50:23,435] {bash_operator.py:126} INFO - Treinando modelo test_LR
[2020-06-12 16:50:23,435] {bash_operator.py:126} INFO - Tabela salva em /home/vinicius/Documents/Projetos/Claro/Piloto/git_Homologação/data/output/model_output_91423.csv
[2020-06-12 16:50:23,435] {bash_operator.py:126} INFO - Traceback (most recent call last):
[2020-06-12 16:50:23,435] {bash_operator.py:126} INFO -   File "/home/vinicius/Documents/Projetos/Claro/Piloto/git_Homologação/src/modeling/run.py", line 106, in <module>
[2020-06-12 16:50:23,435] {bash_operator.py:126} INFO -     save_output(config_model,list_result,output_dict)
[2020-06-12 16:50:23,436] {bash_operator.py:126} INFO -   File "/home/vinicius/Documents/Projetos/Claro/Piloto/git_Homologação/src/modeling/run.py", line 54, in save_output
[2020-06-12 16:50:23,436] {bash_operator.py:126} INFO -     output_dict['table_path'] = f"{output_table_path}/{output_table_name}"
[2020-06-12 16:50:23,436] {bash_operator.py:126} INFO - NameError: name 'output_table_path' is not defined
[2020-06-12 16:50:23,790] {bash_operator.py:128} INFO - Command exited with return code 1
[2020-06-12 16:50:23,802] {taskinstance.py:1145} ERROR - Bash command failed
Traceback (most recent call last):
  File "/home/vinicius/anaconda3/envs/claro_piloto_homolog/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/vinicius/anaconda3/envs/claro_piloto_homolog/lib/python3.8/site-packages/airflow/operators/bash_operator.py", line 134, in execute
    raise AirflowException("Bash command failed")
airflow.exceptions.AirflowException: Bash command failed
[2020-06-12 16:50:23,804] {taskinstance.py:1168} INFO - Marking task as UP_FOR_RETRY
[2020-06-12 16:50:24,478] {logging_mixin.py:112} INFO - [2020-06-12 16:50:24,478] {local_task_job.py:103} INFO - Task exited with return code 1
