[2020-06-11 03:06:09,959] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: dataops.modeling 2020-06-11T00:00:00+00:00 [queued]>
[2020-06-11 03:06:09,991] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: dataops.modeling 2020-06-11T00:00:00+00:00 [queued]>
[2020-06-11 03:06:09,991] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-11 03:06:09,991] {taskinstance.py:880} INFO - Starting attempt 4 of 7
[2020-06-11 03:06:09,991] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-11 03:06:10,017] {taskinstance.py:900} INFO - Executing <Task(BashOperator): modeling> on 2020-06-11T00:00:00+00:00
[2020-06-11 03:06:10,019] {standard_task_runner.py:53} INFO - Started process 25029 to run task
[2020-06-11 03:06:10,088] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: dataops.modeling 2020-06-11T00:00:00+00:00 [running]> vinicius-Latitude-3480
[2020-06-11 03:06:10,115] {bash_operator.py:82} INFO - Tmp dir root location: 
 /tmp
[2020-06-11 03:06:10,116] {bash_operator.py:105} INFO - Temporary script location: /tmp/airflowtmpkpm1ipjn/modelingwrcvypm2
[2020-06-11 03:06:10,116] {bash_operator.py:115} INFO - Running command: python /home/vinicius/Documents/Projetos/Claro/Piloto/git_Homologação/src/modeling/run.py
[2020-06-11 03:06:10,126] {bash_operator.py:122} INFO - Output:
[2020-06-11 03:06:52,709] {helpers.py:325} INFO - Sending Signals.SIGTERM to GPID 25029
[2020-06-11 03:06:52,709] {taskinstance.py:954} ERROR - Received SIGTERM. Terminating subprocesses.
[2020-06-11 03:06:52,709] {bash_operator.py:140} INFO - Sending SIGTERM signal to bash process group
[2020-06-11 03:06:52,735] {taskinstance.py:1145} ERROR - Task received SIGTERM signal
Traceback (most recent call last):
  File "/home/vinicius/anaconda3/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/vinicius/anaconda3/lib/python3.7/site-packages/airflow/operators/bash_operator.py", line 124, in execute
    for line in iter(self.sub_process.stdout.readline, b''):
  File "/home/vinicius/anaconda3/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 956, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2020-06-11 03:06:52,737] {taskinstance.py:1168} INFO - Marking task as UP_FOR_RETRY
[2020-06-11 03:06:52,808] {helpers.py:291} INFO - Process psutil.Process(pid=25040, status='terminated') (25040) terminated with exit code None
[2020-06-11 03:06:52,809] {helpers.py:291} INFO - Process psutil.Process(pid=25029, status='terminated') (25029) terminated with exit code 1
[2020-06-11 03:06:52,904] {helpers.py:291} INFO - Process psutil.Process(pid=25043, status='terminated') (25043) terminated with exit code None
